import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import rankdata
from itertools import combinations

# Plot diagnostics for saved ListMLE predictions. These arrays are generated by
# listMLE/listsize/test.py or listMLE/lora/test_lora.py.
# Assumes:
# targets.shape = (197, 64, 4)
# preds.shape   = (197, 64, 4)

targets = np.load("best_model_listmle_listsize_4_targets.npy")
preds = np.load("best_model_listmle_listsize_4_preds.npy")

assert targets.shape == preds.shape, "targets and preds must have same shape"
assert targets.ndim == 3, "Expected shape: (num_batches_or_groups, batch_size, list_size)"

# Flatten first two dimensions:
# (197, 64, 4) -> (197*64, 4)
targets_flat = targets.reshape(-1, targets.shape[-1])
preds_flat = preds.reshape(-1, preds.shape[-1])

num_lists, list_size = targets_flat.shape

# ============================================================
# 1. Rank heatmap
# ============================================================

true_ranks_all = []
pred_ranks_all = []

for p, t in zip(preds_flat, targets_flat):
    # Rank 1 = highest / best value
    true_ranks = rankdata(-t, method="ordinal")
    pred_ranks = rankdata(-p, method="ordinal")

    true_ranks_all.extend(true_ranks)
    pred_ranks_all.extend(pred_ranks)

true_ranks_all = np.array(true_ranks_all)
pred_ranks_all = np.array(pred_ranks_all)

heatmap = np.zeros((list_size, list_size), dtype=int)

for tr, pr in zip(true_ranks_all, pred_ranks_all):
    # Rows are true ranks and columns are predicted ranks. Perfect ranking
    # would concentrate counts along the diagonal.
    heatmap[int(tr) - 1, int(pr) - 1] += 1

plt.figure(figsize=(6, 5))
plt.imshow(heatmap, aspect="auto")
plt.colorbar(label="Count")

plt.xticks(np.arange(list_size), np.arange(1, list_size + 1))
plt.yticks(np.arange(list_size), np.arange(1, list_size + 1))

plt.xlabel("Predicted rank")
plt.ylabel("True rank")
plt.title("Predicted Rank vs. True Rank Heatmap")

for i in range(list_size):
    for j in range(list_size):
        plt.text(
            j,
            i,
            str(heatmap[i, j]),
            ha="center",
            va="center"
        )

plt.tight_layout()
plt.savefig("rank_heatmap_1million.png", dpi=300)
plt.show()


# ============================================================
# 2. Top-1 accuracy
# ============================================================

top1_correct = np.argmax(preds_flat, axis=1) == np.argmax(targets_flat, axis=1)
top1_accuracy = top1_correct.mean()

print(f"Top-1 accuracy: {top1_accuracy:.4f}")

plt.figure(figsize=(4, 5))
plt.bar(["Top-1 Accuracy"], [top1_accuracy])
plt.ylim(0, 1)
plt.ylabel("Accuracy")
plt.title("Top-1 Accuracy")

plt.text(
    0,
    min(top1_accuracy + 0.03, 0.98),
    f"{top1_accuracy:.3f}",
    ha="center"
)

plt.tight_layout()
plt.savefig("top1_accuracy_1million.png", dpi=300)
plt.show()


# ============================================================
# 3. Pairwise accuracy distribution
# ============================================================

pairwise_accs = []

for p, t in zip(preds_flat, targets_flat):
    correct = 0
    total = 0

    for i, j in combinations(range(list_size), 2):
        # Skip ties in target
        if t[i] == t[j]:
            continue

        # Pairwise accuracy asks whether the model preserves the true order for
        # each pair, independent of the exact score magnitudes.
        pred_order = p[i] > p[j]
        target_order = t[i] > t[j]

        correct += int(pred_order == target_order)
        total += 1

    if total > 0:
        pairwise_accs.append(correct / total)

pairwise_accs = np.array(pairwise_accs)

print(f"Mean pairwise accuracy: {pairwise_accs.mean():.4f}")
print(f"Std pairwise accuracy: {pairwise_accs.std():.4f}")
print(f"Number of lists used: {len(pairwise_accs)} / {num_lists}")

plt.figure(figsize=(6, 5))
plt.hist(
    pairwise_accs,
    bins=np.linspace(0, 1, 11),
    edgecolor="black"
)

plt.axvline(
    pairwise_accs.mean(),
    linestyle="--",
    label=f"Mean = {pairwise_accs.mean():.3f}"
)

plt.xlabel("Pairwise accuracy per list")
plt.ylabel("Number of lists")
plt.title("Pairwise Accuracy Distribution")
plt.legend()

plt.tight_layout()
plt.savefig("pairwise_accuracy_distribution_1million.png", dpi=300)
plt.show()


# ============================================================
# 4. Discrete pairwise accuracy bar plot
# Useful because list size = 4, so each list has 6 pairs
# ============================================================

values, counts = np.unique(pairwise_accs, return_counts=True)

plt.figure(figsize=(6, 5))
plt.bar(values, counts, width=0.08, edgecolor="black")

plt.xlabel("Pairwise accuracy per list")
plt.ylabel("Number of lists")
plt.title("Discrete Pairwise Accuracy Distribution")

if list_size == 4:
    plt.xticks(
        np.arange(0, 1.01, 1 / 6),
        [f"{i}/6" for i in range(7)],
        rotation=45
    )
else:
    plt.xticks(values, [f"{v:.2f}" for v in values], rotation=45)

plt.tight_layout()
plt.savefig("pairwise_accuracy_discrete_1million.png", dpi=300)
plt.show()
